### ISSUE TITLE
Longitude , Latitude BUG

### ISSUE THREAD

**Issue by sj-lt** [pantadeusz/mhe#1]
/**
 * @brief reads solution from input stream
 *
 * overrides the >> operator, so you can write ```cin >> solution```
 */
std::istream &operator>>(std::istream &s, solution_t &sol) {
  nlohmann::json sol_json;
  sol_json = sol_json.parse(s);
  std::vector<city_t> cities;
  for (auto element : sol_json["cities"]) {
    city_t c{element[0], element[1], element[2]};    **<--- should be {elem[0],elem[2],elem[1]}**
    cities.push_back(c);
  }
  solution_t solnew(cities);
  sol = solnew;
  return s;
}

**Comment by pantadeusz** [comment]
indeed the order was bad, but in the city_t class. Thank you. Fixed in 3c56c7f 
Waiting for review.

**Comment by slutkiewicz** [comment]
That was it. Earlier there was also wrong long lat order in html scel but it was in earlier version .
